disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Kingbreaker Forge"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2006-01-02"
copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Filip Sufitchi"
email = "filip@kingbreakerforge.com"
headline = "I'm only human"
bio = "A little bit about you"
image = "filip.jpg"


[[params.author.links]]
email = "mailto:filip@kingbreakerforge.com"

[[params.author.links]]
link = "https://kingbreakerforge.com/"
