disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Kingbreaker Forge"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2006-01-02"
copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Kingbreaker Forge"
email = "filip@kingbreakerforge.com"
headline = "Unique handcrafted blades and forging art"
bio = "A little bit about you"
# image = "img/coa-filip.png"


[[params.author.links]]
email = "mailto:filip@kingbreakerforge.com"

[[params.author.links]]
link = "https://kingbreakerforge.com/"
