[[main]]
none = "none"

[[main]]
name = "About Me"
pre = "heart"
pageRef = "/pages/about"
weight = 1

[[main]]
name = "Blog"
pre = "comment"
pageRef = "/blog"
weight = 2


[[main]]
name = "Inventory"
pre = "bars"
pageRef = "/items"
weight = 3


[[footer]]
none = "none"
