[[main]]
none = "none"

[[main]]
name = "Inventory"
pre = "list"
pageRef = "inventory"
identifier = "xEkcmXjSCV"
weight = 2

[[main]]
name = "About Me"
pre = "heart"
pageRef = "about"
identifier = "tQrBGFrjHA"
weight = 1

[[footer]]
none = "none"
